services:
  # Base de datos Postgres
  db:
    image: postgres:15-alpine
    container_name: postgres_inventarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ESTO ES LO QUE FALTABA:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventarios"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Tu API en Go
  api:
    build: .
    container_name: go_api_inventarios
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: inventarios

volumes:
  postgres_data: